#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/owrt-peer-discover

start_service() {
    config_load owrt-peer
    local enabled
    config_get enabled main enabled 0
    [ "$enabled" -eq 0 ] && return 0

    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall -9 owrt-peer-discover 2>/dev/null
    killall -9 tcpdump 2>/dev/null
    killall -9 nc 2>/dev/null
}
